env:
  es6: true
  node: true
  amd: true
extends: 'eslint:recommended'
rules:
  no-multi-spaces: 0
  space-in-parens: 0
  array-bracket-spacing: 0
  computed-property-spacing: 0
  key-spacing: 0
  no-var: 2
  indent:
    - 2
    - 2
  brace-style:
    - 2
    - 'stroustrup'
    -
      allowSingleLine: false
